### ISSUE TITLE
CLI: Improve User Experience

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/proposals#11]
**Author**: Ruslan Aksenov

### Summary of the feature being proposed
Refactor and improve a number of items in CLI, such as semantics, commands discoverability, integration with bash/zsh, rethink global vs command options, improve UI, support config file for default option values

### What value does this feature bring to Temporal?
Makes the Temporal CLI friendlier for both new and experienced users

### Are you willing to implement this feature yourself?
Yes

**Comment by rylandg** [comment]
I think this all seems reasonable. In the future I would prefer a few examples in the proposal. Please continue by creating a PR that adheres to the template!

**Comment by feedmeapples** [comment]
closing as many of the proposal are merged & implemented
