### ISSUE TITLE
Service: Support mTLS certificate refreshing

### ISSUE THREAD

**Issue by robzienert** [temporalio/proposals#16]
**Author**: @robzienert

### Summary of the feature being proposed

Support mTLS certificates being refreshed.

### What value does this feature bring to Temporal?

This would help organizations that use short-lived, rotating mTLS certificates adopt Temporal. Users of Hashicorp Vault, Amazon CM, or other technologies would find this particular proposal useful.

Our specific use case refreshes certificates every _T_ minutes in `/dev/shm`. I'm open to specifics of implementation (file watch, polling, etc).

### Are you willing to implement this feature yourself?

Yes.

**Comment by sergeybykov** [comment]
Sorry, somehow I didn't see this when I was opening #1162.

@robzienert, I'm literally starting looking into this right now. If you are still interested, let's cooperate.

**Comment by robzienert** [comment]
@sergeybykov Sure, would love to help where I can.

I realize this isn't part of the proposal, however: I'm currently trying to get our certs to work as-is without refreshing and am not having much success - is it possible that the TLSProvider could be extensible? If I could use our certificate service directly, I wouldn't need to export CAs and so-on, and would be able to provide certificates directly without Temporal trying to generate its own.

**Comment by sergeybykov** [comment]
Have you tried [`WithTLSConfigFactory` server option](https://github.com/temporalio/temporal/blob/d8c74c925f983c7e38802ea12313eb709f1e85c1/temporal/server_option.go#L76)? It enables overriding of the TLS config provider, and should let you define TLS config on all four ends the way you need.

**Comment by robzienert** [comment]
That extension works great, feel bad I missed it before! Our refresh intervals are infrequent enough that we're not in immediate need of certificate refreshing.

**Comment by sergeybykov** [comment]
BTW, #1288 enabled dynamic serving of certs on a per-connection basis. We still plan to change the included cert provider to update certs without restarting server.
