### ISSUE TITLE
SDK: Python

### ISSUE THREAD

**Issue by bbkgh** [temporalio/proposals#18]
**Author**: Babak

### Summary of the feature being proposed
Implement a SDK for Python

### What value does this feature bring to Temporal?
I think many companies (including ourselves) are using Python as their main scripting/programming language. Also in some areas like DevOps and Data Science  (that are two important potential areas for Temporal) using Python as a convenient scripting language is so popular. I think providing Python and other popular languages SDKs makes a big leap in Temporal customers.

### Are you willing to implement this feature yourself?
Unfortunately I don't have the resources. It will be good if there exists any sample tutorial/reference implementation for implementing Temporal SDKs (language agnostic or not). Also i (and probably future viewer of this issue) am willing to contribute to Python SDK project if you start that.

**Comment by sw-yx** [comment]
yes, this is in development - please join the python channel in slack, and watch this repo https://github.com/firdaus/temporal-python-sdk
