### ISSUE TITLE
SDK: Python, but based on the Rust SDK-of-SDKs (sdk-core)

### ISSUE THREAD

**Issue by pypt** [temporalio/proposals#20]
**Author**: Linas Valiukas

### Summary of the feature being proposed

Given that the unofficial SDK by @firdaus is going to be no longer supported by the author, I'd like to propose rolling out a new Python SDK based on the Rust SDK (https://github.com/temporalio/sdk-core).

### What value does this feature bring to Temporal?

* SDK in the [second most popular programming language](https://insights.stackoverflow.com/survey/2020#technology-programming-scripting-and-markup-languages-all-respondents)

### Are you willing to implement this feature yourself?

Depends - I'd like to learn more about what implementing such a Python SDK would entail.

**Comment by Sushisource** [comment]
Currently core implements the basics of running workflows (Starting, completing, timing out, failing, etc) as well as running activities, timers, and handling signals.

The Node SDK does run on top of core. It uses https://neon-bindings.com/ to do so. For Python my eye has been on https://github.com/PyO3/pyo3 to call down into core.

You can see where the Node SDK does it here: https://github.com/temporalio/sdk-node/blob/main/packages/worker/native/src/lib.rs which exports functions that get defined in a sort of typescript header file here https://github.com/temporalio/sdk-node/blob/main/packages/worker/native/index.d.ts which is then in turn used the normal way in the rest of the code.

**Comment by pypt** [comment]
Thanks again, give me some time to stare at the Rust SDK for a bit (and skim through the Rust book as well).

**Comment by bergundy** [comment]
@pypt keep in mind that the Core API is still considered unstable.
We're prioritizing features that are likely to affect the API like core<>lang tracing and logging and sticky Workflow execution so hopefully we'll feel like it's stabilizing after we deal with the bulk of these open issues.

**Comment by pypt** [comment]
Sorry for the delay, it took me a while to read through that Rust book on weekends :)

Here's a rough sketch of the Python SDK that could be put together:

https://github.com/pypt/pytemporalio

The general idea is to write a bunch of "wrapper" (in lieu of a better term) structs that would be PyO3-enabled (i.e. set up to be exposed as Python classes), and through `From` / `TryFrom` traits the objects of those classes would able to be converted back and forth between Python-enabled structs-slash-classes and "native" structs that the Temporal SDK could use, e.g.:

https://github.com/pypt/pytemporalio/blob/4e103fcabdcb79fa773df839b9e8ef90eb2373ec/src/pollers/gateway.rs#L18-L52

(Maybe there's a way to generate PyO3 classes using protobuf files, or perhaps by inspecting AST, but I figured that just writing a bunch of boilerplate would be quicker / easier for v0.1.0.)

To call the native methods asynchronously, I'm using [`pyo3_asyncio`](https://docs.rs/pyo3-asyncio/0.14.0/pyo3_asyncio/):

https://github.com/pypt/pytemporalio/blob/4e103fcabdcb79fa773df839b9e8ef90eb2373ec/src/lib.rs#L149-L166

Everything gets exposed as a bunch of Python (sub)modules:

https://github.com/pypt/pytemporalio/blob/4e103fcabdcb79fa773df839b9e8ef90eb2373ec/src/lib.rs#L248-L339

and then the idea that there would be another set of Python wrappers on top of those PyO3-generated modules - that's to make things more user friendly, e.g. add typing annotations, docstrings, convert ugly `oneof` classes to Python enums (PyO3 doesn't support Rust's enums apparently), etc.

As of now the module's finished parts kind of work already:

```
➜   cat test.py 
#!/usr/bin/env python3

import asyncio
import datetime

import pytemporalio


async def test_init():
    long_poll_timeout = datetime.timedelta(seconds=3)
    gateway_opts = pytemporalio.pollers.gateway.ServerGatewayOptions(target_url='http://test', namespace='default', identity='test', worker_binary_id='test', long_poll_timeout=long_poll_timeout)
    opts = pytemporalio.CoreInitOptions(gateway_opts=gateway_opts, max_cached_workflows=3)
    await pytemporalio.init(opts)

asyncio.run(test_init())

➜   python3 test.py 
Traceback (most recent call last):
  File "/home/pypt/.rust-targets/pytemporalio/debug/test.py", line 15, in <module>
    asyncio.run(test_init())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pypt/.rust-targets/pytemporalio/debug/test.py", line 13, in test_init
    await pytemporalio.init(opts)
OSError: Server connection error: tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("dns error", Custom { kind: Other, error: "failed to lookup address information: Name or service not known" })))
```

but a bunch of work needs to be done to finish writing wrappers for the rest of the structs / methods, plus making the module into a product (adding Rust / Python tests, READMEs, generating docs, CI, etc.)

**Comment by Sushisource** [comment]
@pypt Wow this is really neat! Thanks for this really substantial contribution. You've already given me some possible answers to a handful of outstanding questions I've had about how we might do things like call the async Rust functions.

I also do have a tip for how you can (relatively) easily get rid of all your handwritten wrapper structs. Import the protos from core as a git subtree/module. Then, take a look at what I've done in `build.rs` for Core:  https://github.com/temporalio/sdk-core/blob/master/build.rs -- as you can see, it is possible to instruct the protobuf generator to attach attribute macros (or whatever else) to the generated output (more [here](https://docs.rs/prost-build/0.8.0/prost_build/struct.Config.html) -- you won't need tonic, just use prost directly). Bam, now you can have the generator output structs with the needed `pyclass` attributes. 

That won't quite do it, though... the last remaining annoying parts are the `Duration` fields and the methods. Both could be accomplished by writing our own attribute macro (say, `#[pymirror]`), and having the proto generator spit out classes annotated with that. That macro would replace normal `Durations` with `pyo3` ones, and it can also autogenerate the `new` and `From` / `TryFrom` implementations. Writing procedural macros can be a bit hard to get started with but I think it'd be a really solid approach here.

On the more boring side of things, I'd also recommend using `clippy` and `rustfmt` :smile: 

We are planning on getting started in earnest on the Python SDK in the not too distant future. When we do, we're going to want that work to be owned under https://github.com/temporalio. Are you open to the idea of potentially moving this work under our organization if it pans out and you're interested in continuing to work on it?

Thanks again for this great work!

**Comment by bergundy** [comment]
@pypt awesome work, this is exactly the direction we were thinking of going.
As @Sushisource pointed out, it might be best to serialize the protos in rust and deserialize in python to avoid all of the conversion code, that's what we ended up doing in node and it save a lot of boilerplate conversion code.

Developing a fully fledged SDK with testing, CI, documentation and samples, requires months of work and maintenance over time.
Due to the importance of the Python SDK, we plan on officially maintaining it under the Temporal org, if you're interested in collaborating with us, we'd be more than happy.

Thanks for this!

**Comment by devonkinghorn** [comment]
My company is adopting Temporal for Golang. What is the chance that there is a Python SDK in the next six months?

**Comment by Sushisource** [comment]
@devonkinghorn Very high, as we've started work on it: https://github.com/temporalio/sdk-python

Thanks for reminding me about this issue! I'll be closing it since development has started. See also https://github.com/temporalio/proposals/pull/50
