### ISSUE TITLE
.Net SDK

### ISSUE THREAD

**Issue by jimitndiaye** [temporalio/proposals#51]
**Author**:

### Summary of the feature being proposed
A C#/.Net SDK for Temporal
### What value does this feature bring to Temporal?
Wider reach - .Net is one of the most popular development platforms around
### Are you willing to implement this feature yourself?
Unfortunately I'm not familiar enough with Temporal's inner workings to even begin to attempt that.  I have come across [this](https://github.com/nforgeio/neonKUBE/blob/master/Lib/Neon.Temporal/README.md) implementation in progress but it is currently in alpha

**Comment by lorensr** [comment]
We're working on one—it's currently in internal design stage. We'll update in #dotnet-sdk channel in the community Slack when the design is up for external review!

**Comment by josh-berry** [comment]
Going to close this ticket, since this proposal has already been accepted and is well underway here: https://github.com/temporalio/sdk-dotnet
