### ISSUE TITLE
Integrate an Open Policy Agent based REGO Authorizer

### ISSUE THREAD

**Issue by ghaskins** [temporalio/proposals#81]
**Author**: Greg Haskins

### Summary of the feature being proposed
Introduce first-class support for [REGO](https://www.openpolicyagent.org/docs/latest/policy-language/) as an Authorizer to augment the current Noop and Default Authorizers.  In this model, users opting into the new Authorizer may do so purely with configuration/rego without implementing a custom Plugin and the requisite custom build that it implies.

OPA already offers a Go SDK, so it is a natural fit for the Temporal ecosystem.

The proposal would be to add a new "opa" type to augment the existing "" (noop) and "default" Authorizers.  Users configuring the "opa" Authorizer must supply additional configuration as a rego document.   A rego policy that equates to the current "default" Authorizer will minimally be provided as an example.  Additional examples may be included, as well.

The ability to override any built-in Authorizer with a plugin will be retained as it currently functions.

### What value does this feature bring to Temporal?
1) Users may customize the Authorizer logic without requiring a custom build of Temporal.
2) Users may express their Authorizer logic by leveraging the power of REGO, a fit-for-purpose policy grammar.

### Are you willing to implement this feature yourself?
Yes

**Comment by mbernier** [comment]
Adding a note to follow up from Slack convo - seems related to https://github.com/temporalio/temporal/pull/3702#issuecomment-1426594901

**Comment by nickwilliams-codynamic** [comment]
Thanks for tagging that other PR @mbernier. 

Do you know if there is a preference on which option might be the best way to go? Or would there be a plan to support both methods?

On my PR @dnr and I had some discussions around making my change a `http` authorizer - where Temporal effectively delegates authorization decisions to a third-party via a HTTP call, and only does authorization enforcement based on the response.

I think the proposal here is really good (so long as we could provide the rego files at runtime through volumes/binds/configmaps and not need a custom docker image build). However it does remove a couple of features I was hoping to get out of the `http` authorizer.

From my point of view I see the tradeoff with this approach is:

__PROS__
- Consumers don't need to run another piece of software for auth (like OPA)
- Config could be provided at runtime, unlike the default authorizer which requires a custom docker image

__CONS__
- Consumers are forced to use REGO - whereas with `httpAuthorizer` they can use anything (e.g. rego, imperative language, XACML, PolicyServer)
- No option for additional features that come with external policy decision makers (e.g. [OPA decision logs](https://www.openpolicyagent.org/docs/latest/management-decision-logs/))
- No way to dynamically update policies without restarting temporal nodes? I think this would be the case, but could maybe be worked around? (Although in the case of running in k8s it seems likely that people would use configmaps and volumes that would force a restart when the config map changed)
